/**
 * Created by Zaccary on 20/06/2015.
 */

export const SET_LAYOUT = 'SET_LAYOUT';
export const SET_SETTINGS_MODAL = 'SET_SETTINGS_MODAL';
export const SET_SETTINGS_ERROR = 'SET_SETTINGS_ERROR';


export const ROOM_LOAD = 'ROOM_LOAD';
export const ROOM_EMOJI = 'ROOM_EMOJI';
export const SET_ROOM_SETTINGS = 'SET_ROOM_SETTINGS';
export const SET_CLIENT_USER = 'SET_CLIENT_USER';
export const MESSAGE_ADD = 'MESSAGE_ADD';
export const MESSAGE_SEND = 'MESSAGE_SEND';
export const USER_CONNECT = 'USER_CONNECT';
export const USER_UPDATE_USERLIST = 'USER_UPDATE_USERLIST';
export const USER_DISCONNECT = 'USER_DISCONNECT';
export const USER_UPDATE_HANDLE = 'USER_UPDATE_HANDLE';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_SET_NOTIFICATIONS = 'USER_SET_NOTIFICATIONS';
export const USER_SET_THEME = 'USER_SET_THEME';
export const USER_SET_UNREAD_MESSAGES = 'USER_SET_UNREAD_MESSAGES';
export const USER_SET_BROADCAST_QUALITY = 'USER_SET_BROADCAST_QUALITY';


export const SET_USER_LIST_OPTION_LIST = 'SET_USER_LIST_OPTION_LIST';
export const STREAM_REMOTE_DESTROY = 'STREAM_REMOTE_DESTROY';
export const STREAM_REMOTE_HANGUP = 'STREAM_REMOTE_HANGUP';
export const STREAM_REMOTE_RESUME = 'STREAM_REMOTE_RESUME';
export const STREAM_HANGUP_ALL = 'STREAM_HANGUP_ALL';
export const STREAM_RESUME_ALL = 'STREAM_RESUME_ALL';
export const STREAM_AUDIO_TOGGLE_MUTE = 'STREAM_AUDIO_TOGGLE_MUTE';
export const STREAM_AUDIO_TOGGLE_MUTE_ALL = 'STREAM_AUDIO_TOGGLE_MUTE_ALL';
export const STREAM_AUDIO_SET_GLOBAL_VOLUME = 'STREAM_AUDIO_SET_GLOBAL_VOLUME';
export const STREAM_LOCAL_CAN_BROADCAST = 'STREAM_LOCAL_CAN_BROADCAST';
export const STREAM_LOCAL_ADD = 'STREAM_LOCAL_ADD';
export const STREAM_LOCAL_DESTROY = 'STREAM_LOCAL_DESTROY';
export const STREAM_REMOTE_ADD = 'STREAM_REMOTE_ADD';
export const SET_STREAM_OPTIONS_STATE = 'SET_STREAM_OPTIONS_STATE';
export const SET_MESSAGE_SOUND = 'SET_MESSAGE_SOUND';
export const SET_SHOW_USERLIST = 'SET_SHOW_USERLIST';
export const SET_CHAT_INPUT_VALUE = 'SET_CHAT_INPUT_VALUE';
export const SET_WINDOW_IS_VISIBLE = 'SET_WINDOW_IS_VISIBLE';
export const SET_UNREAD_MESSAGES = 'SET_UNREAD_MESSAGES';
export const SET_CLIENT_PTT = 'SET_CLIENT_PTT';
export const SET_DEFAULT_PTT = 'SET_DEFAULT_PTT';
export const SET_REMOTE_STREAM_VOLUME = 'SET_REMOTE_STREAM_VOLUME';
export const STREAM_AUDIO_SET_ACTIVE = 'STREAM_AUDIO_SET_ACTIVE';
export const STREAM_SHOW_VOLUME_SLIDER = 'STREAM_SHOW_VOLUME_SLIDER';
export const STREAM_SET_LOADING = 'STREAM_SET_LOADING';
export const SET_LOCAL_AUDIO_ACTIVE = 'SET_LOCAL_AUDIO_ACTIVE';
export const RESUME_AUDIO_CONTEXT = 'RESUME_AUDIO_CONTEXT';
export const STREAM_SET_QUALITY = 'STREAM_SET_QUALITY';
export const SET_QUALITY_OPTIONS = 'SET_QUALITY_OPTIONS';
export const SET_MESSAGE_HISTORY = 'SET_MESSAGE_HISTORY';

// private messages
export const PM_START_CONVERSATION = 'PM_START_CONVERSATION';
export const PM_SELECT_CONVERSATION = 'PM_SELECT_CONVERSATION';
export const PM_REMOVE_CONVERSATION = 'PM_REMOVE_CONVERSATION';
export const PM_OPEN_MENU = 'PM_OPEN_MENU';
export const PM_CLOSE_CONVERSATION = 'PM_CLOSE_CONVERSATION';
export const PM_SET_CONVO_READ = 'PM_SET_CONVO_READ';

// Chat
export const CHAT_SET_USERS = 'CHAT_SET_USERS';
export const CHAT_SET_SETTINGS = 'CHAT_SET_SETTINGS';
export const CHAT_CLEAR_FEED = 'CHAT_CLEAR_FEED';
export const CHAT_SET_SCROLL = 'CHAT_SET_SCROLL';
export const CHAT_SET_SCROLL_FIXED = 'CHAT_SET_SCROLL_FIXED';

export const RESTORE_MESSAGE = 'RESTORE_MESSAGE';
export const SELECT_CHAT_TAB = 'SELECT_CHAT_TAB';
export const ADD_PRIVATE_MESSAGE = 'ADD_PRIVATE_MESSAGE';
export const SET_EMOJI_SEARCH = 'SET_EMOJI_SEARCH';
export const SET_EMOJI_RESULT_SELECTED = 'SET_EMOJI_RESULT_SELECTED';
export const SET_BANLIST = 'SET_BANLIST';

// modals
export const HANDLE_MODAL_STATE = 'HANDLE_MODAL_STATE';
export const BANLIST_MODAL_STATE = 'BANLIST_MODAL_STATE';
export const MEDIA_MODAL_STATE = 'MEDIA_MODAL_STATE';
export const MEDIA_MODAL_TYPE = 'MEDIA_MODAL_TYPE';
export const MEDIA_MODAL_SET_DEVICE_ID = 'MEDIA_MODAL_SET_DEVICE_ID';
export const MEDIA_MODAL_SET_AUDIO_PTT = 'MEDIA_MODAL_SET_AUDIO_PTT';
export const MEDIA_MODAL_LOADING = 'MEDIA_MODAL_LOADING';
export const MODAL_ERROR = 'MODAL_ERROR';
export const SET_JOIN_CONDITION_MODAL = 'SET_JOIN_CONDITION_MODAL';
export const SET_PROFILE_MODAL = 'SET_PROFILE_MODAL';
export const SET_IGNORE_MODAL = 'SET_IGNORE_MODAL';
export const SET_BAN_MODAL = 'SET_BAN_MODAL';


// sessions
export const SESSION_ID_SAVE = 'SESSION_ID_SAVE';
export const SESSION_IS_RECONNECTING = 'SESSION_IS_RECONNECTING';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const PAUSE_NOTIFICATIONS = 'PAUSE_NOTIFICATIONS';
export const RESUME_NOTIFICATION = 'RESUME_NOTIFICATION';

export const CLIENT_UPDATE_HANDLE = 'CLIENT_UPDATE_HANDLE';

export const USER_SET = 'USER_SET';
export const USER_ACT_TOKEN_SET = 'USER_ACT_TOKEN_SET';
export const USER_LOG_IN = 'USER_LOG_IN';
export const HANDLE_MODAL_OPEN = 'HANDLE_MODAL_OPEN';
export const HANDLE_MODAL_CLOSE = 'HANDLE_MODAL_CLOSE';
export const HANDLE_MODAL_ERROR = 'HANDLE_MODAL_ERROR';
export const ACCOUNT_MODAL_STATE = 'ACCOUNT_MODAL_STATE';
export const INFO_MODAL_STATE = 'INFO_MODAL_STATE';
export const REPORT_MODAL_STATE = 'REPORT_MODAL_STATE';
export const SET_BROADCAST_RESTRICTED = 'SET_BROADCAST_RESTRICTED';
export const SET_EMOJI_PICKER = 'SET_EMOJI_PICKER';
export const INSERT_EMOJI = 'INSERT_EMOJI';
export const UPDATE_IGNORE = 'UPDATE_IGNORE';
export const USER_SET_PLAY_VIDEOS = 'USER_SET_PLAY_VIDEOS';

// Youtube
export const YOUTUBE_MODAL_STATE = 'YOUTUBE_MODAL_STATE';
export const YOUTUBE_SET_RESULTS = 'YOUTUBE_SET_RESULTS';
export const YOUTUBE_SET_VIDEO = 'YOUTUBE_SET_VIDEO';
export const YOUTUBE_SET_OPTIONS = 'YOUTUBE_SET_OPTIONS';
export const YOUTUBE_CLIENT_CLOSE_VIDEO = 'YOUTUBE_CLIENT_CLOSE_VIDEO';
export const YOUTUBE_ROOM_CLOSE_VIDEO = 'YOUTUBE_ROOM_CLOSE_VIDEO';
export const YOUTUBE_SET_VOLUME = 'YOUTUBE_SET_VOLUME';
export const YOUTUBE_SET_RESULTS_LOADING = 'YOUTUBE_SET_RESULTS_LOADING';
export const YOUTUBE_SET_VOLUME_CONTROL = 'YOUTUBE_SET_VOLUME_CONTROL';
export const YOUTUBE_SET_VIDEO_PAUSED = 'YOUTUBE_SET_VIDEO_PAUSED';
export const YOUTUBE_SET_VIDEO_RESUMED = 'YOUTUBE_SET_VIDEO_RESUMED';
export const YOUTUBE_SET_PLAYLIST = 'YOUTUBE_SET_PLAYLIST';
export const YOUTUBE_SET_PLAYLIST_ITEM_OPTIONS = 'YOUTUBE_SET_PLAYLIST_ITEM_OPTIONS';
export const YOUTUBE_CLEAR_SEARCH = 'YOUTUBE_CLEAR_SEARCH';
export const YOUTUBE_SET_VIDEO_SEEK = 'YOUTUBE_SET_VIDEO_SEEK';

// Push
export const PUSH_SET_MANAGER = 'PUSH_SET_MANAGER';
export const PUSH_SET_PUBLIC_KEY = 'PUSH_SET_PUBLIC_KEY';

export const PROFILE_SET = 'PROFILE_SET';
export const PROFILE_SET_NEW = 'PROFILE_SET_NEW';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_SET_IGNORE_ITEM = 'PROFILE_SET_IGNORE_ITEM';

// roles
export const ROLE_UPDATE = 'ROLE_UPDATE';
export const ROLES_SET = 'ROLES_SET';
export const ROLES_FETCH = 'ROLES_FETCH';
export const ROLES_SAVE = 'ROLES_SAVE';
export const ROLES_REMOVE = 'ROLES_REMOVE';
export const ENROLLMENTS_FETCH = 'ENROLLMENTS_FETCH';
export const ENROLLMENTS_SET = 'ENROLLMENTS_SET';
export const ENROLLMENT_USER_ADD = 'ENROLLMENT_USER_ADD';
export const ENROLLMENT_USER_ADD_FAILED = 'ENROLLMENT_USER_ADD_FAILED';
export const ENROLL_USER = 'ENROLL_USER';
export const UNENROLL_USER = 'UNENROLL_USER';
