import { library } from '@fortawesome/fontawesome-svg-core';

import {
  faHeart,
  faUser,
  faLock,
  faSnowman,
  faSignInAlt,
  faUserPlus,
  faVideoSlash,
  faBullhorn,
  faExclamationCircle,
  faGift,
  faEnvelope,
  faCheckSquare,
  faBars,
  faVolumeUp,
  faVolumeDown,
  faVolumeOff,
  faPlus,
  faTag,
  faStar,
  faStarHalfAlt,
  faShieldAlt,
  faCircle,
  faCertificate,
  faGripVertical,
  faCog,
  faSmile,
  faTrashAlt,
  faEllipsisV,
  faTimes,
  faFilm,
  faEyeSlash,
  faVideo,
} from '@fortawesome/free-solid-svg-icons';

export default () => {
  const icons = [
    faSmile,
    faTrashAlt,
    faEllipsisV,
    faTimes,
    faFilm,
    faHeart,
    faUser,
    faEyeSlash,
    faLock,
    faSnowman,
    faSignInAlt,
    faUserPlus,
    faBullhorn,
    faVideo,
    faVideoSlash,
    faExclamationCircle,
    faGift,
    faEnvelope,
    faCheckSquare,
    faBars,
    faVolumeUp,
    faVolumeOff,
    faVolumeDown,
    faPlus,
    faTag,
    faStar,
    faStarHalfAlt,
    faShieldAlt,
    faCircle,
    faCertificate,
    faGripVertical,
    faCog,
  ];

  library.add(...icons);
};
