import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faSmile,
  faTrashAlt,
  faEllipsisV,
  faTimes,
  faFilm,
  faUser,
  faEyeSlash,
  faWebcam,
  faWebcamSlash,
  faSquare,
} from '@fortawesome/pro-regular-svg-icons';

import {
  faHeart,
  faUser as faUserSolid,
  faLock,
  faSnowman,
  faSignInAlt,
  faUserPlus,
  faVideoSlash,
  faBullhorn,
  faExclamationCircle,
  faGift,
  faEnvelope,
  faCheckSquare,
  faBars,
  faVolumeUp,
  faVolume,
  faVolumeDown,
  faVolumeOff,
  faPlus,
  faTag,
  faStar,
  faStarHalfAlt,
  faShield,
  faShieldAlt,
  faDiamond,
  faHexagon,
  faTriangle,
  faSquare as faSquareSolid,
  faCircle,
  faOctagon,
  faBadge,
  faGripVertical,
  faCog,
} from '@fortawesome/pro-solid-svg-icons';

export default () => {
  const icons = [
    faSmile,
    faTrashAlt,
    faEllipsisV,
    faTimes,
    faFilm,
    faHeart,
    faUserSolid,
    faUser,
    faEyeSlash,
    faLock,
    faSnowman,
    faSignInAlt,
    faUserPlus,
    faVideoSlash,
    faBullhorn,
    faWebcam,
    faWebcamSlash,
    faExclamationCircle,
    faGift,
    faEnvelope,
    faSquare,
    faCheckSquare,
    faBars,
    faVolumeUp,
    faVolumeOff,
    faVolume,
    faVolumeDown,
    faPlus,
    faTag,
    faStar,
    faStarHalfAlt,
    faShield,
    faShieldAlt,
    faDiamond,
    faHexagon,
    faOctagon,
    faTriangle,
    faSquareSolid,
    faCircle,
    faBadge,
    faGripVertical,
    faCog,
  ];

  library.add(...icons);
};
